name: Spark Livy Server Build
on:
  push:
    branches:
      - master
env:
  MAVEN_OPTS: -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.http.retryHandler.class=standard -Dmaven.wagon.http.retryHandler.count=3
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        spark_version: ["3.0"]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3

      - 
        name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: |
            /root/.m2/repository
            !/root/.m2/repository/org/apache/livy
          key: ${{ runner.os }}-maven-${{ hashFiles('pom.xml', '*/pom.xml', 'thriftserver/*/pom.xml', 'core/*/pom.xml', 'repl/*/pom.xml', 'scala-api/*/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      -
        name: Set profile based on matrix
        run: |
          if [ "${{ matrix.spark_version }}" = "3.0" ]; then echo "mvn_profile=-Pspark-3.0" >> $GITHUB_ENV; fi
      - 
        name: Build with Maven
        shell: bash
        run: |
          mvn clean -DskipTests -DskipITs -Dmaven.javadoc.skip=true -Pspark-3.0 package
          rm -rf ./release-staging
          mkdir ./release-staging
          LIVY_VERSION="0.8.0-incubating-SNAPSHOT"
          BIN_ARCHIVE="apache-livy-$LIVY_VERSION-bin.zip"
          echo "Copying and signing regular binary distribution"
          ls -l ./assembly/target
          cp ./assembly/target/$BIN_ARCHIVE ./release-staging
          echo "" | $GPG --passphrase-fd 0 --armour --output ./release-staging/$BIN_ARCHIVE.asc --detach-sig ./release-staging/$BIN_ARCHIVE
          echo "" | $GPG --passphrase-fd 0 --print-md SHA512 ./release-staging/$BIN_ARCHIVE > ./release-staging/$BIN_ARCHIVE.sha512
          
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./dev/docker/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/spark-livy-3.3.2:1.1