name: Spark Livy Server Build
on:
  push:
    branches:
      - master
env:
  MAVEN_OPTS: -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.http.retryHandler.class=standard -Dmaven.wagon.http.retryHandler.count=3
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        spark_version: ["3.0"]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3

      - 
        name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: |
            /root/.m2/repository
            !/root/.m2/repository/org/apache/livy
          key: ${{ runner.os }}-maven-${{ hashFiles('pom.xml', '*/pom.xml', 'thriftserver/*/pom.xml', 'core/*/pom.xml', 'repl/*/pom.xml', 'scala-api/*/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      -
        name: Set profile based on matrix
        run: |
          if [ "${{ matrix.spark_version }}" = "3.0" ]; then echo "mvn_profile=-Pspark-3.0" >> $GITHUB_ENV; fi
      - 
        name: Build with Maven
        run: mvn -DskipTests -Dmaven.javadoc.skip=true package
      - run: ls -l ./server/target
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./dev/docker/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/spark-livy-3.3.2:1.1